import AppShell from '@components/AppShell';
import { Comfortaa } from 'next/font/google';

const c = Comfortaa({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={c.className}>
        <AppShell>
          
          {children}
          
          </AppShell>
      </body>
    </html>
  );
}
